### ISSUE TITLE
Suurballe and Disjoint Path Finding

### ISSUE THREAD

**Issue by crl-n** [Caruychen/42Hive-Lem_in#10]
This issue is another question or maybe rather just me thinking aloud. My aim with this issue is mostly to start a discussion about how to understand/conceptualize the problem Lem-in is asking us to solve. What do I mean by that? Well, first of all, I don't think we've misconceptualized or misunderstood the problem. Nothing of the sort. We know what we need to do. Get those ants from source to sink. And we know we can use Ford-Fulkerson, Edmonds-Karp and/or Dinic's to do this. That's clear. But I've learned there are other approaches to the specific problem Lem-in presents. That's where Suurballe and disjoint path finding comes in.

There are far less resources on Suurballe than on all the max flow algorithms, but you can find a pretty good description of Suurballe's algorithm [here](http://www.macfreek.nl/memory/Disjoint_Path_Finding). Basically, what it does is find K number of shortest disjoint paths between two nodes in a graph. By disjoint it is meant that the paths don't share either edges or vertices. Well, as far as I've understood, these are exactly the types of paths we need to use in our algorithm. And I'm under the impression that the augmenting paths in Edmonds-Karp are vertice-disjoint paths, although I might be completely wrong about this!

What seems really interesting is that basically by modifying Edmonds-Karp or any of the other max flow algos we can do what we need to do. By modifying I'm refering to that the real output we want from Edmonds-Karp is not really the value for the max flow, but instead the list of augmenting paths that make up the max flow. Similarily, an algo like Suurballe could be modified to produce an exhaustive list of disjoint paths that could then be used to assign ants to.

I guess my point is that Lem-in is a really interesting problem that isn't just a maximum flow problem. In fact, it seems to me it falls kind of in between some common graph problems. And a second point is that we could look into Suurballe as well, and see what makes sense to use and if there are any differences between these two approaches.

Maybe we could discuss this more if we meet up some day to go over the solving, once you are back. As always, let me know what you think!

**Comment by Caruychen** [comment]
Thanks for sharing these articles, they are an interesting read.

From just a quick assessment of the Bhandari algorithm and the Suurballe algorithms, in the end they all have what seems like the same material outcome. In fact my analysis of Edmunds-Karp algorithm effectively feels like the same problem solving process.

All the different algorithms have some slightly different approaches to solving what is generally a multiple path finding problem. They all seek to identify the most efficient paths to maximise flow through. They have different implementations in how they deal with path augmentation. But looking at them from a distance, and blurring my eyes a bit, they seem to work the same way in the bigger picture. 

I feel like an analogy is like painkillers, you have a headache, and you could you Ibuprofen, or Paracetamol. They might target different chemistries and neural pathways, but all deal with the same problem in the end.

So the key difference in what to consider or not, for me at least, is how easily they lend themselves to a technical implementation. I'll be honest, I think Suurballes algorithm is very inelegant and my intuition tells me that implementing duplicating intermediate paths will be an unnecessarily complex task in C. It's likely to be a rather intractable problem. I'm sure it can be done, I think Will had done something a bit similar, only that the entire graph was duplicated.

In fact Bhandari's algorithm is a much closer representation of what I had in mind. It's also quite similar, almost identical to what I had seen from an Edmunds Karp algorithm. I note that the fact that each path only has a capacity of one ant has made the implementation much simpler. Hopefully this all makes sense.

I agree that this is also more than just a max flow problem. In fact, the max flow solving process is only the beginning, it is necessary but far from sufficient.

I'm really looking forward to talking about the solving process with you, there's been a bunch sitting in my head for a while! I'll note some things here
- Max flow is just the beginning. The max flow itself will also need to account for the specific number of ants coming through. I.e. the max number of path finding iterations to be done for augmentation is limited by the number of ants. For example, considering the path shown in the article, the max flow path set for two ants is very different for just one ant.
- The identified paths will also need to be extracted and stored in an array of paths. Once the path identifying is done, we don't need the graph anymore, and it's more efficient to compute on some more linearly shaped arrays.
- We will then need to determine the order of paths in which to send ants down, and how many in each path. This should be a relatively straightforward numeric minimisation problem.

**Comment by crl-n** [comment]
Sweet, looking forward to have you back!

As for storing the paths, will it be sufficient to just store each of them as indices in a vec?

By the way, another cool thing I stumbled upon is Multi-Agent Pathfinding (MAPF). What we are doing seems to me to resemble centralized MAPF.

**Comment by Caruychen** [comment]
Okay that's pretty interesting! I'll have a look into that when I get a chance, thanks!

In terms of storing the paths, yea I think indices should be sufficient. That's just an educated guess though, we will see how it goes.

There's one other thing that came to mind that I need to mention as well. Specifically, in circumstances where the graph might have bottlenecks. It's not big problem, and I think is easily solved, but I wanted to present it since isn't a trivial problem either. Consider this kind of graph:

 Start
  / \
 O   O
  \ /
   O
  / \
 O   O
  \ /
  End

If I'm not mistaken, most of the max flow algorithms would end up giving two paths (hopefully it is obvious). The immediate issue is then clear, the middle node becomes a bottleneck, and we have paths that share the same vertex. 

I think it's possible that Suurballes algorithm overcomes this problem (this is just conjecture however, I don't know for sure).

However, we should have a simpler solution. It can be found at the stage when we need to store the paths. That is, to simply drop any additional paths that form bottlenecks, and keep the shortest path overall. I believe this should effectively achieve the same result. 

There are some specific implementation details needed to make sure we only keep the shortest path through the bottleneck. First thing being, using a shortest path algorithm process to extract the already identified paths (this should be fairly quick)

The node struct will need an additional binary field, e.g we can name it "extracted".

Hopefully, this is a valid solution? If you have considered this scenario, I'd love to hear your thoughts. Are the any issues you notice? Perhaps any other snags that escape me?

**Comment by crl-n** [comment]
Interesting stuff!

Yeah, I think you are right. Most max flow algorithms would find two paths.

While looking into this problem I realized something I hadn't before. In the examples of Edmonds-Karp I looked at it was always the edges that had a capacity - not the vertices. I believe this is the reason max flow algorithms would find two paths in the example graph. Nodes essentially don't have any capacity, only edges do.

How to fix it? I stumbled upon this Stack Overflow post](https://stackoverflow.com/questions/8751327/edmonds-karp-algorithm-for-a-graph-which-has-nodes-with-flow-capacities)) where somebody solved a similar issue by treating nodes as edges. Quite an interesting solution IMO. However, in our case both the vertices and edges have the same capacity of 1, right? I think this means that treating nodes as edges wouldn't really do anything.

I think that in our case, it should be sufficient to make sure that no paths share any nodes except for source and sink nodes. As far as I can tell, it also shouldn't cause any other issues.

Basically, I think that if we just figure out a way to make sure our Edmonds-Karp looks for node-disjoint (or vertex-disjoint) paths and **not** edge-disjoint paths we should be finding only one path in the type of graph you described.

This builds on the assumption that the first path to be added will always be the shortest one, which I believe will be the case, since Edmonds-Karp uses breadth-first-search and all edges are the same length (meaning the first path that the search finds should always be the shortest).

As for how to save the information of whether the a node already is in a path or not, I think it you're right that it could be a binary variable in the node struct. Another alternative is to use a helper boolean array to keep track of which nodes are already extracted.

Hope that mades sense! Soon we get to discuss this issue irl, which will probably make it all clearer.

**Comment by Caruychen** [comment]
Yes you are right, there should be some simple ways to avoid paths sharing the same node. Using BFS for searching paths will indeed return the shortest paths first.

Interestingly, the stack overflow solution you've shown be seems to be exactly what Suurballe's algorithm does. Seems to be a commonly used solution. But I also agree that we can avoid it.

This is mainly because of the fact that all node capacities are at 1 (which can be easily used to imply a flow capacity of 1 to the edges). The capacity / flow state is just a binary state, so it's either full or empty. In other words, if there is flow, then it's full. Otherwise, when there is no flow it is empty. 

In all the examples we've seen of the algorithms, there is usually greater than 1 capacity. Which is means the nodes could still have capacity, even if there is flow, and I think that's when the proposed stack overflow solution is needed.

There is some inherent logic in the simple 1 capacity nodes that, I believe, allow our implementation to be node-disjoint.

I've drawn out a little example below, hopefully the attachment works here. I also hope it makes sense!

![image](https://user-images.githubusercontent.com/58788447/178626663-f4997189-e891-4293-93ac-cdf20db5c4b0.jpeg)
![image](https://user-images.githubusercontent.com/58788447/178626681-aae2ef66-3207-4121-bb63-9383aea4c115.jpeg)
